// Renders ONE registry control based on its `control` type. This is the heart of
// the parity rule: the control panel is generated by iterating whatever the API
// returns from /api/parameters — nothing here is hardcoded per parameter.
//
// `showHelp` (default true) renders the registry `help` text INLINE under the
// control, so every parameter's meaning is visible without hovering for a tooltip.

export default function ParameterControl({ spec, value, onChange, showHelp = true }) {
  const label = spec.unit ? `${spec.label} (${spec.unit})` : spec.label;
  const help = showHelp && spec.help ? <p className="ctl-help">{spec.help}</p> : null;

  if (spec.control === 'bool') {
    return (
      <div className="ctl-wrap">
        <label className="ctl ctl-bool" title={spec.help}>
          <span className="ctl-label">{label}</span>
          <input
            type="checkbox"
            checked={Boolean(value)}
            onChange={(e) => onChange(e.target.checked)}
          />
        </label>
        {help}
      </div>
    );
  }

  if (spec.control === 'enum') {
    return (
      <div className="ctl-wrap">
        <label className="ctl ctl-enum" title={spec.help}>
          <span className="ctl-label">{label}</span>
          <select value={value ?? ''} onChange={(e) => onChange(e.target.value)}>
            {(spec.choices || []).map((c) => (
              <option key={c} value={c}>
                {c}
              </option>
            ))}
          </select>
        </label>
        {help}
      </div>
    );
  }

  // int / float -> slider (with a live numeric readout).
  const min = spec.minimum ?? 0;
  const max = spec.maximum ?? 1;
  const step = spec.step ?? (spec.control === 'int' ? 1 : 0.01);
  const num = Number(value);
  return (
    <div className="ctl-wrap">
      <label className="ctl ctl-slider" title={spec.help}>
        <span className="ctl-label">
          {label} <span className="ctl-value">{Number.isFinite(num) ? num : '—'}</span>
        </span>
        <input
          type="range"
          min={min}
          max={max}
          step={step}
          value={Number.isFinite(num) ? num : min}
          onChange={(e) =>
            onChange(spec.control === 'int' ? parseInt(e.target.value, 10) : parseFloat(e.target.value))
          }
        />
      </label>
      {help}
    </div>
  );
}
