"""Frontend 1 — trame + pyvista (server-side VTK rendering).

This UI calls the Python ``core`` DIRECTLY (trame is server-side); it does NOT go
through the HTTP API for compute. It reaches feature parity with the React
frontend and adds the full clinician workflow:

  * Controls are generated by iterating the parameter registry (``control_specs``)
    — the param list is never hardcoded, so the two UIs cannot drift.
  * A SIDE selector driven purely by ``session.sides`` (``['full']`` for a single
    scan, ``['left','right']`` for a bilateral one — never assumes a bone).
  * An "Apply / Recompute" button re-runs ``core.pipeline`` with the CURRENT
    parameter values and swaps in the freshly computed geometry.
  * A Mode A / Mode B toggle. Mode A = single-side cortical thickness. Mode B adds
    a per-side THICKNESS view AND a two-side signed-DEVIATION view.
  * SHARE panel + UI SWITCHER: reads runtime config (``outputs/public_urls.json``)
    and shows the current public URL plus a button to jump to the OTHER UI.
  * UPLOAD (all formats): ``.zip .nii .nii.gz .stl .ply .obj .vtp`` — branches on
    the result (mesh session => view/compare only, single-sided => a "Full"
    selector, bilateral => Left/Right).
  * HOVER TOOLTIP: hovering the 3D surface reads the picked point's scalar
    (thickness_mm / deviation_mm, mm) + position, with a local readout vs the
    map mean.
  * EXPORT panel: pick formats (png/tiff/jpg/stl/ply/obj/vtp/dicom), a DPI, and a
    camera pose (azimuth/elevation/roll/zoom) -> ``core.export.export_bundle`` ->
    real per-format download links.
  * MANUAL ANCHOR (Mode B): translation x/y/z mm + rotation deg (a 4x4 nudge) plus
    a reference/target swap ("which side on top"), recomputed on apply.

Heavy compute runs on a background thread so the server stays responsive.

Run:  .venv/bin/python -m app_trame.app   (serves on http://localhost:8081)
"""

from __future__ import annotations

import json
import sys
import threading
import traceback
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import numpy as np  # noqa: E402
import pyvista as pv  # noqa: E402
from pyvista.trame.ui import plotter_ui  # noqa: E402
from trame.app import get_server  # noqa: E402
from trame.ui.vuetify3 import SinglePageWithDrawerLayout  # noqa: E402
from trame.widgets import html  # noqa: E402
from trame.widgets import vuetify3 as v3  # noqa: E402

import core.parameters as P  # noqa: E402
import core.viz.slice as mpr  # noqa: E402  (shared slice math — byte-identical to the API)
from app_trame.controls import control_specs  # noqa: E402
from app_trame.scene import build_deviation_scene, build_thickness_scene  # noqa: E402
from core import pipeline  # noqa: E402
from core.export import export_bundle  # noqa: E402
from core.ingest import is_mesh  # noqa: E402

pv.OFF_SCREEN = True

WORKDIR = ROOT / "data" / "raw"
EXPORTS_DIR = ROOT / "outputs" / "exports"
EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
PUBLIC_URLS = ROOT / "outputs" / "public_urls.json"
# Prefer the shipped DE-IDENTIFIED demo (NIfTI carries no patient tags); fall
# back to a local raw archive only if it is absent. So the demo shows a generic,
# dynamic series name (read from the scan) rather than any patient/protocol text.
_DEIDENTIFIED_DEMO = ROOT / "data" / "demo" / "shoulder_demo.nii.gz"
_RAW_DEMO_DIR = ROOT / "Bilateral Omuz BT Jul 4 2026"
DEMO_ZIP = _DEIDENTIFIED_DEMO if _DEIDENTIFIED_DEMO.exists() else (
    next(_RAW_DEMO_DIR.glob("*.zip"), None) if _RAW_DEMO_DIR.exists() else None)

# Fallback local URLs for the UI switcher when no tunnel config is present.
FALLBACK_TRAME_URL = "http://localhost:8081"
FALLBACK_REACT_URL = "http://localhost:5173"

server = get_server(client_type="vue3")
state, ctrl = server.state, server.controller

# Serve the exports directory over the trame HTTP server so download links work
# from within the running UI (files land under /downloads/...).
server.serve["downloads"] = str(EXPORTS_DIR)

PLOTTER = pv.Plotter(off_screen=True)

# --------------------------------------------------------------------------- #
# Server-side session. Guarded by a lock: the compute thread reads it while the
# UI may reload it via upload.
#   sides: name -> {arr, spacing, offset_xyz, side}  (volume side)
#              or  {mesh, side, offset_xyz}           (bare-mesh side)
#   is_mesh: True when the session holds only a surface (no volume to measure)
# --------------------------------------------------------------------------- #
SESSION: dict = {"arr": None, "spacing": None, "meta": None, "sides": {},
                 "is_mesh": False}
_LOCK = threading.Lock()
_LAST_MESH = {"thickness": None, "deviation": None}

# Monotonic session generation: bumped whenever a new scan/mesh is adopted, so a
# thumbnail cache keyed by (generation, side) is invalidated automatically.
_SESSION_GEN = 0
# (generation, side) -> [{label, volume_cm3, boneness, thumb}] region previews.
_THUMB_CACHE: dict[tuple[int, str], list[dict]] = {}
_THUMB_LOCK = threading.Lock()


# --------------------------------------------------------------------------- #
# Runtime config (Share panel + UI switcher). Read the same file the API uses.
# --------------------------------------------------------------------------- #
def read_public_config() -> dict:
    """Mirror of ``/api/config``: public share URLs from public_urls.json."""
    pub: dict = {}
    if PUBLIC_URLS.exists():
        try:
            pub = json.loads(PUBLIC_URLS.read_text())
        except Exception:  # noqa: BLE001
            pub = {}
    return {
        "app": "3Dorth",
        "react_url": pub.get("react_url"),
        "trame_url": pub.get("trame_url"),
        "public": bool(pub.get("react_url") or pub.get("trame_url")),
    }


def _bump_session_gen() -> int:
    """Advance the session generation (invalidates the thumbnail cache)."""
    global _SESSION_GEN
    _SESSION_GEN += 1
    return _SESSION_GEN


def _adopt_volume_session(arr, spacing, meta, layout="auto") -> None:
    sides = pipeline.split_sides(arr, spacing, layout=layout)
    with _LOCK:
        SESSION.update(arr=arr, spacing=spacing, meta=meta, sides=sides,
                       is_mesh=False)
    _bump_session_gen()


def _adopt_mesh_session(mesh, meta) -> None:
    sides = {"mesh": {"mesh": mesh, "side": "mesh", "offset_xyz": (0.0, 0.0, 0.0)}}
    with _LOCK:
        SESSION.update(arr=None, spacing=None, meta=meta, sides=sides,
                       is_mesh=True)
    _bump_session_gen()


def _load_source(path: Path, layout: str = "auto") -> None:
    """Ingest an uploaded/demo path; branch mesh vs volume like /api/upload."""
    if is_mesh(path):
        mesh = pipeline.load_mesh_source(path)
        meta = {"format": path.suffix.lstrip("."), "kind": "mesh",
                "n_points": int(mesh.n_points)}
        _adopt_mesh_session(mesh, meta)
    else:
        arr, spacing, meta = pipeline.load_volume_from_source(path, WORKDIR)
        _adopt_volume_session(arr, spacing, meta, layout=layout)


def _side_names() -> list[str]:
    with _LOCK:
        return list(SESSION["sides"].keys())


def _refresh_session_ui() -> None:
    """Push session-derived UI state (side options, mesh flag, sensible defaults)."""
    names = _side_names()
    is_mesh_sess = bool(SESSION.get("is_mesh"))
    labels = {"left": "Left", "right": "Right", "full": "Full", "mesh": "Mesh"}
    opts = [{"title": labels.get(n, n.capitalize()), "value": n} for n in names]
    bilateral = set(names) == {"left", "right"}

    state.side_options = opts
    state.session_sides = names
    state.is_mesh_session = is_mesh_sess
    state.is_bilateral = bilateral
    # Keep the active selectors valid for the current session.
    if state.side not in names:
        state.side = names[0] if names else "full"
    if bilateral:
        state.ref_side, state.tgt_side = "left", "right"
    elif names:
        # Non-bilateral: reference/target both fall back to the only side.
        state.ref_side = state.tgt_side = names[0]
    # A bare-mesh session cannot do Mode-A thickness (needs a volume wall).
    if is_mesh_sess and state.mode == "A":
        state.mode = "B"
    state.meta_html = _meta_html()
    # A fresh scan invalidates any previously shown region previews.
    state.region_thumbs = []
    state.region_thumbs_side = ""
    state.region_thumbs_loading = False
    state.region_thumbs_msg = ""
    state.region_label = None
    # Re-point the MPR viewer at the new session's active volume (or hide it for a
    # bare-mesh session). Safe to call inside a `with state` block.
    _mpr_reset_for_side()


def _downloads_url(thumb: str | None) -> str | None:
    """Rewrite a pipeline ``/api/exports/<file>`` URL onto the trame server's
    ``/downloads`` mount (the exports dir is served there). ``None`` stays None."""
    if not thumb:
        return None
    return f"/downloads/{Path(thumb).name}"


def load_region_thumbnails(*_a, **_k) -> None:
    """Compute (or serve from cache) small per-region previews for the active
    thickness side, on a background thread, and push them to the UI.

    Calls ``core.pipeline.region_thumbnails`` DIRECTLY (trame is server-side).
    Files land under ``outputs/exports`` (served at ``/downloads``). Cached per
    (session generation, side). Skipped for a bare-mesh session (no volume
    regions) and for the deviation view. Render takes ~5-10 s; the UI shows a
    spinner meanwhile.
    """
    if bool(SESSION.get("is_mesh")):
        return
    if state.mode == "B" and state.b_view == "deviation":
        return
    side_key = state.side
    with _LOCK:
        gen = _SESSION_GEN
        side = SESSION["sides"].get(side_key)
    if side is None or side.get("arr") is None:
        return

    cache_key = (gen, side_key)
    with _THUMB_LOCK:
        cached = _THUMB_CACHE.get(cache_key)
    if cached is not None:
        with state:
            state.region_thumbs = cached
            state.region_thumbs_side = side_key
            state.region_thumbs_loading = False
            state.region_thumbs_msg = (
                f"{len(cached)} region(s)." if cached else "No bone regions found."
            )
        state.flush()
        return

    with state:
        state.region_thumbs_loading = True
        state.region_thumbs = []
        state.region_thumbs_side = side_key
        state.region_thumbs_msg = "Rendering region previews… (~5–10 s)"
    state.flush()

    def _job():
        try:
            thumbs = pipeline.region_thumbnails(
                side["arr"], side["spacing"], P.default_parameters(),
                EXPORTS_DIR, f"{gen}_{side_key}",
            )
            for t in thumbs:
                t["thumb"] = _downloads_url(t.get("thumb"))
            with _THUMB_LOCK:
                _THUMB_CACHE[cache_key] = thumbs
            # Only apply if the session/side is still what we computed for.
            with _LOCK:
                still_current = (_SESSION_GEN == gen and state.side == side_key)
            with state:
                if still_current:
                    state.region_thumbs = thumbs
                    state.region_thumbs_side = side_key
                state.region_thumbs_loading = False
                state.region_thumbs_msg = (
                    f"{len(thumbs)} region(s)." if thumbs
                    else "No bone regions found.")
            state.flush()
        except Exception as e:  # noqa: BLE001
            traceback.print_exc()
            with state:
                state.region_thumbs_loading = False
                state.region_thumbs_msg = f"Preview render failed: {e}"
            state.flush()

    threading.Thread(target=_job, daemon=True).start()


ctrl.load_region_thumbnails = load_region_thumbnails


def select_region(label, **_k):
    """Pick a region from a thumbnail; store it and trigger a recompute so the
    thickness map switches to that structure (parity with the React click)."""
    try:
        state.region_label = int(label)
    except (TypeError, ValueError):
        return
    schedule_recompute()


ctrl.select_region = select_region


# --------------------------------------------------------------------------- #
# State: registry defaults + UI-only knobs.
# --------------------------------------------------------------------------- #
for _c in control_specs():
    state[_c["key"]] = _c["default"]

state.mode = "A"                 # "A" or "B"
state.side = "left"              # active side for thickness views
state.ref_side = "left"          # Mode B reference
state.tgt_side = "right"         # Mode B target
state.b_view = "thickness"       # Mode B sub-view: "thickness" or "deviation"
state.status = "idle"            # "idle" | "computing" | "done" | "error"
state.status_msg = "Ready."
state.stats_html = ""
state.meta_html = ""
state.side_options = [{"title": "Left", "value": "left"},
                      {"title": "Right", "value": "right"}]
state.session_sides = ["left", "right"]
state.is_mesh_session = False
state.is_bilateral = True
state.upload_file = None

# --- Region thumbnails (visual picker) ------------------------------------ #
# Small rendered previews per connected bone region, computed via
# core.pipeline.region_thumbnails and served from /downloads. Cached per
# (session-generation, side) so switching side / re-opening doesn't recompute.
state.region_thumbs = []          # [{label, volume_cm3, boneness, thumb: url|None}]
state.region_thumbs_side = ""     # which side the shown thumbs belong to
state.region_thumbs_loading = False
state.region_thumbs_msg = ""
state.region_label = None         # active region (None => auto-pick largest)

# --- Share panel / UI switcher -------------------------------------------- #
_cfg = read_public_config()
state.cfg_public = _cfg["public"]
state.cfg_trame_url = _cfg["trame_url"] or ""
state.cfg_react_url = _cfg["react_url"] or ""
# The URL for THIS ui and the OTHER ui (this is the trame UI).
state.share_url = _cfg["trame_url"] or FALLBACK_TRAME_URL
state.other_ui_name = "React"
state.other_ui_url = _cfg["react_url"] or FALLBACK_REACT_URL

# --- Hover tooltip -------------------------------------------------------- #
state.hover_active = False
state.hover_html = ""
state.hover_x = 0
state.hover_y = 0

# --- Export panel --------------------------------------------------------- #
state.export_formats = ["png", "vtp"]
state.export_format_choices = ["png", "tiff", "jpg", "stl", "ply", "obj",
                               "vtp", "dicom"]
state.export_dpi = 300
state.cam_azimuth = 0.0
state.cam_elevation = 0.0
state.cam_roll = 0.0
state.cam_zoom = 1.0
state.export_busy = False
state.export_msg = ""
state.export_links = []          # [{fmt, url}]

# --- Manual anchor (Mode B) ---------------------------------------------- #
state.manual_tx = 0.0
state.manual_ty = 0.0
state.manual_tz = 0.0
state.manual_rx = 0.0            # rotation deg about x
state.manual_ry = 0.0
state.manual_rz = 0.0
state.manual_enabled = False

# --- MPR (multiplanar reformat) viewer ----------------------------------- #
# Three 2D slice images (axial/coronal/sagittal) beside the 3D view, rendered by
# the SAME core.viz.slice functions the FastAPI /slice endpoint uses, so a slice
# at (plane, index, window, level) is byte-identical across both frontends. A
# shared crosshair {ix,iy,iz,window,level} lives in trame state; each plane has a
# slider, and clicking the 3D surface drives the crosshair via world_to_voxel +
# slices_from_voxel. Planes are ARRAY-ORIENTED (labeled as such); we never assert
# radiological A/P/S/I.
state.mpr_available = False       # true once a volume side is loaded
state.mpr_side = ""               # which side the shown slices belong to
state.mpr_ix = 0                  # crosshair voxel (ix,iy,iz) = (x,y,z) index
state.mpr_iy = 0
state.mpr_iz = 0
state.mpr_window = mpr.BONE_WINDOW
state.mpr_level = mpr.BONE_LEVEL
state.mpr_n_axial = 1             # slice counts per plane (from volume-info)
state.mpr_n_coronal = 1
state.mpr_n_sagittal = 1
state.mpr_idx_axial = 0           # active slice index per plane (clamped)
state.mpr_idx_coronal = 0
state.mpr_idx_sagittal = 0
state.mpr_img_axial = ""          # data:image/png;base64,... for each plane
state.mpr_img_coronal = ""
state.mpr_img_sagittal = ""
state.mpr_note = ("Research / de-identified — not for diagnostic use. Planes are "
                  "array-oriented (no radiological A/P/S/I laterality).")

# plane -> (crosshair-index state key, per-plane index state key, n-slices key)
_MPR_PLANE_STATE = {
    "axial": ("mpr_iz", "mpr_idx_axial", "mpr_n_axial"),
    "coronal": ("mpr_iy", "mpr_idx_coronal", "mpr_n_coronal"),
    "sagittal": ("mpr_ix", "mpr_idx_sagittal", "mpr_n_sagittal"),
}


def _mpr_active_side() -> dict | None:
    """Return the volume-side dict feeding the MPR viewer (None for mesh/empty).

    Uses the thickness side selector; falls back to the reference side (Mode B) or
    the first volume side so the panels always show something for a volume scan.
    """
    if bool(SESSION.get("is_mesh")):
        return None
    with _LOCK:
        sides = dict(SESSION["sides"])
    for key in (state.side, state.ref_side, *sides.keys()):
        sd = sides.get(key)
        if sd is not None and sd.get("arr") is not None:
            state.mpr_side = key
            return sd
    return None


def _mpr_render_plane(side: dict, plane: str) -> str:
    """Render one plane to a base64 data URI via the shared slice pipeline."""
    import base64
    idx_key = _MPR_PLANE_STATE[plane][1]
    index = int(state[idx_key])
    png = mpr.render_slice_png(
        side["arr"], side["spacing"], plane, index,
        window=float(state.mpr_window), level=float(state.mpr_level), max_dim=384,
    )
    return "data:image/png;base64," + base64.b64encode(png).decode("ascii")


def _mpr_refresh_images(*_a, **_k) -> None:
    """Re-render all three slice PNGs from the current crosshair/window/level."""
    side = _mpr_active_side()
    if side is None:
        with state:
            state.mpr_available = False
        state.flush()
        return
    with state:
        state.mpr_available = True
        state.mpr_img_axial = _mpr_render_plane(side, "axial")
        state.mpr_img_coronal = _mpr_render_plane(side, "coronal")
        state.mpr_img_sagittal = _mpr_render_plane(side, "sagittal")
    state.flush()


def _mpr_sync_from_voxel(ijk) -> None:
    """Adopt a voxel (ix,iy,iz): set crosshair + per-plane slice indices (clamped),
    exactly like the API's slices_from_voxel, then re-render the three panels."""
    side = _mpr_active_side()
    if side is None:
        return
    shape = side["arr"].shape  # (nz, ny, nx)
    ix, iy, iz = (int(v) for v in ijk)
    sl = mpr.slices_from_voxel((ix, iy, iz), shape)
    with state:
        state.mpr_ix = mpr.clamp_index(shape, "sagittal", ix)
        state.mpr_iy = mpr.clamp_index(shape, "coronal", iy)
        state.mpr_iz = mpr.clamp_index(shape, "axial", iz)
        state.mpr_idx_axial = sl["axial"]
        state.mpr_idx_coronal = sl["coronal"]
        state.mpr_idx_sagittal = sl["sagittal"]
    _mpr_refresh_images()


def _mpr_reset_for_side(*_a, **_k) -> None:
    """Reset MPR extents + crosshair to the center of the active volume side."""
    side = _mpr_active_side()
    if side is None:
        with state:
            state.mpr_available = False
        state.flush()
        return
    info = mpr.volume_info(side["arr"], side["spacing"], side["offset_xyz"],
                           side.get("side", state.mpr_side))
    nz, ny, nx = info["shape_zyx"]
    with state:
        state.mpr_available = True
        state.mpr_window = info["default_window"]
        state.mpr_level = info["default_level"]
        state.mpr_n_axial = info["n_slices"]["axial"]
        state.mpr_n_coronal = info["n_slices"]["coronal"]
        state.mpr_n_sagittal = info["n_slices"]["sagittal"]
    _mpr_sync_from_voxel((nx // 2, ny // 2, nz // 2))


def _mpr_on_plane_index_change(*_a, **_k) -> None:
    """A plane slider moved: mirror it into the crosshair voxel and re-render.

    axial idx -> iz, coronal idx -> iy, sagittal idx -> ix (per the fixed plane↔axis
    map). Keeps the crosshair and the three panels in sync from either direction.
    """
    with state:
        state.mpr_iz = int(state.mpr_idx_axial)
        state.mpr_iy = int(state.mpr_idx_coronal)
        state.mpr_ix = int(state.mpr_idx_sagittal)
    _mpr_refresh_images()


ctrl.mpr_refresh = _mpr_refresh_images
ctrl.mpr_reset = _mpr_reset_for_side


def _params_from_state() -> "P.Parameters":
    updates = {c["key"]: state[c["key"]] for c in control_specs()
               if state[c["key"]] is not None}
    return P.Parameters(**updates)


def _manual_transform_matrix() -> list[list[float]] | None:
    """Compose the operator nudge (rotations then translation) into a 4x4 list.

    Returns ``None`` when the nudge is disabled or effectively identity so the
    backend takes its untouched auto-registration path.
    """
    if not state.manual_enabled:
        return None
    tx, ty, tz = float(state.manual_tx), float(state.manual_ty), float(state.manual_tz)
    rx, ry, rz = (np.deg2rad(float(state.manual_rx)),
                  np.deg2rad(float(state.manual_ry)),
                  np.deg2rad(float(state.manual_rz)))
    if not any((tx, ty, tz, rx, ry, rz)):
        return None

    def _rot(axis: str, a: float) -> np.ndarray:
        c, s = np.cos(a), np.sin(a)
        R = np.eye(4)
        if axis == "x":
            R[1, 1], R[1, 2], R[2, 1], R[2, 2] = c, -s, s, c
        elif axis == "y":
            R[0, 0], R[0, 2], R[2, 0], R[2, 2] = c, s, -s, c
        else:  # z
            R[0, 0], R[0, 1], R[1, 0], R[1, 1] = c, -s, s, c
        return R

    M = _rot("z", rz) @ _rot("y", ry) @ _rot("x", rx)
    M[0, 3], M[1, 3], M[2, 3] = tx, ty, tz
    return M.tolist()


# --------------------------------------------------------------------------- #
# Stats / meta rendering (HTML, no overlap: simple definition rows).
# --------------------------------------------------------------------------- #
def _stat_rows(title: str, items: list[tuple[str, str]]) -> str:
    rows = "".join(
        f"<div style='display:flex;justify-content:space-between;gap:12px;"
        f"padding:1px 0;font-size:12px;line-height:1.5'>"
        f"<span style='color:#555'>{k}</span>"
        f"<span style='font-variant-numeric:tabular-nums;font-weight:600'>{v}</span></div>"
        for k, v in items
    )
    return (f"<div style='margin-bottom:8px'>"
            f"<div style='font-size:11px;font-weight:700;letter-spacing:.04em;"
            f"text-transform:uppercase;color:#333;margin-bottom:2px'>{title}</div>"
            f"{rows}</div>")


def _meta_html() -> str:
    m = SESSION.get("meta") or {}
    if not m:
        return "<div style='font-size:12px;color:#888'>No scan loaded.</div>"
    if SESSION.get("is_mesh"):
        items = [
            ("Kind", "Surface mesh"),
            ("Format", str(m.get("format", "—"))),
            ("Points", f"{m.get('n_points', 0):,}"),
        ]
        return _stat_rows("Loaded mesh", items)
    items = [
        ("Series", str(m.get("series", "—"))),
        ("Shape (z,y,x)", "×".join(str(s) for s in m.get("shape", []))),
        ("Spacing (mm)", "×".join(str(s) for s in m.get("spacing_mm", []))),
        ("Laterality", str(m.get("laterality", "—"))),
    ]
    return _stat_rows("Loaded scan", items)


# --------------------------------------------------------------------------- #
# Hover picking: read the scalar at the point under the cursor.
# --------------------------------------------------------------------------- #
def _on_hover(point, *_a, **_k):
    """pyvista hover callback: show the picked scalar + position in a tooltip.

    ``point`` is the world-space (x,y,z) under the cursor (or None off-surface).
    We look up the active surface's scalar there and compare it to the map mean.
    """
    key = "deviation_mm" if (state.mode == "B" and state.b_view == "deviation") \
        else "thickness_mm"
    mesh = _LAST_MESH["deviation"] if key == "deviation_mm" else _LAST_MESH["thickness"]
    if point is None or mesh is None or key not in mesh.point_data:
        with state:
            state.hover_active = False
        state.flush()
        return
    try:
        pid = mesh.find_closest_point(np.asarray(point, dtype=float))
        val = float(mesh.point_data[key][pid])
        pos = np.asarray(mesh.points[pid], dtype=float)
        scal = np.asarray(mesh.point_data[key], dtype=float)
        mean = float(np.mean(scal))
    except Exception:  # noqa: BLE001
        return
    unit = "mm"
    label = "Deviation" if key == "deviation_mm" else "Thickness"
    fmt = "%+.2f" if key == "deviation_mm" else "%.2f"
    delta = val - mean
    html_out = (
        f"<div style='font-weight:700;font-size:13px;margin-bottom:2px'>"
        f"{label}: {fmt % val} {unit}</div>"
        f"<div style='font-size:11px;color:#ddd;line-height:1.5'>"
        f"vs map mean {fmt % mean} ({'+' if delta >= 0 else ''}{delta:.2f} {unit})<br>"
        f"x {pos[0]:.1f} · y {pos[1]:.1f} · z {pos[2]:.1f} mm</div>"
    )
    with state:
        state.hover_html = html_out
        state.hover_active = True
    state.flush()


def _on_pick_to_mpr(point, *_a, **_k):
    """Left-click on the 3D surface -> drive the MPR crosshair.

    Mirrors the API's /pick-to-slices: world (x,y,z) mm -> world_to_voxel (with the
    active side's offset) -> slices_from_voxel -> the three 2D panels re-render at
    the picked voxel. Off-surface clicks (point is None) are ignored.
    """
    if point is None:
        return
    side = _mpr_active_side()
    if side is None:
        return
    try:
        ijk = mpr.world_to_voxel(np.asarray(point, dtype=float), side["spacing"],
                                 side["offset_xyz"])
        _mpr_sync_from_voxel(ijk)
    except Exception:  # noqa: BLE001
        traceback.print_exc()


def _enable_hover() -> None:
    """(Re)attach the hover-pick (tooltip) and left-click-pick (MPR crosshair)
    callbacks to the current plotter surface.

    Hover reads the scalar under the cursor (tooltip); a left click drives the MPR
    crosshair via world_to_voxel + slices_from_voxel (byte-identical to the API's
    pick-to-slices). Both are best-effort — the rest of the UI works without them.
    """
    try:
        PLOTTER.disable_picking()
    except Exception:  # noqa: BLE001
        pass
    try:
        PLOTTER.enable_point_picking(
            callback=_on_hover, show_message=False, show_point=False,
            use_picker="hardware", left_clicking=False, picker="point",
        )
    except Exception:  # noqa: BLE001
        # Hover picking is best-effort; the rest of the UI works without it.
        pass
    try:
        # A separate surface-point pick on left click updates the MPR crosshair.
        PLOTTER.enable_surface_point_picking(
            callback=_on_pick_to_mpr, show_message=False, show_point=False,
            left_clicking=True,
        )
    except Exception:  # noqa: BLE001
        # Click-to-MPR is best-effort; sliders still drive the crosshair.
        pass


# --------------------------------------------------------------------------- #
# Realtime auto-recompute plumbing.
#
# Every change to a recompute=True parameter (or to side / mode / b_view /
# reference / target / mirror / manual-anchor) SCHEDULES a debounced background
# recompute — the user never has to click Apply. Rapid changes (e.g. dragging a
# slider) are coalesced: we (re)arm a ~600 ms timer and only the final change
# fires. A monotonically increasing request id supersedes older computes so a
# slow, stale result can never overwrite a newer one (the AbortController
# analogue for a server-side app).
# --------------------------------------------------------------------------- #
RECOMPUTE_DEBOUNCE_S = 0.6

_REQ_LOCK = threading.Lock()
_REQ_COUNTER = 0          # latest scheduled request id (monotonic)
_DEBOUNCE_TIMER: threading.Timer | None = None


def _next_request_id() -> int:
    """Reserve a fresh, strictly-increasing request id (supersedes older ones)."""
    global _REQ_COUNTER
    with _REQ_LOCK:
        _REQ_COUNTER += 1
        return _REQ_COUNTER


def _is_current(req_id: int) -> bool:
    """True while ``req_id`` is still the newest scheduled compute."""
    with _REQ_LOCK:
        return req_id == _REQ_COUNTER


# --------------------------------------------------------------------------- #
# Compute (runs on a background thread).
# --------------------------------------------------------------------------- #
def _compute_worker(req_id: int | None = None):
    # A stale request (superseded before it even started) is dropped.
    if req_id is not None and not _is_current(req_id):
        return
    try:
        params = _params_from_state()
        with _LOCK:
            sides = dict(SESSION["sides"])
            is_mesh_sess = bool(SESSION["is_mesh"])
        if not sides:
            raise RuntimeError("No scan loaded.")

        mode = state.mode
        wants_thickness = mode == "A" or (mode == "B" and state.b_view == "thickness")

        if wants_thickness:
            if is_mesh_sess:
                raise RuntimeError(
                    "This is a surface mesh — thickness needs a volume. "
                    "Use Mode B deviation instead.")
            side_key = state.side
            side = sides.get(side_key)
            if side is None:
                raise RuntimeError(f"Unknown side '{side_key}'.")
            region_label = state.region_label
            try:
                region_label = int(region_label) if region_label is not None else None
            except (TypeError, ValueError):
                region_label = None
            res = pipeline.analyze_thickness(
                side["arr"], side["spacing"], params,
                region_label=region_label, offset_xyz=side["offset_xyz"],
            )
            _LAST_MESH["thickness"] = res["mesh"]
            # Adopt the server's chosen region so the picker reflects reality,
            # WITHOUT re-triggering a recompute (only change when it differs).
            picked = res.get("region_label")
            if picked is not None and state.region_label != picked:
                state.region_label = picked
            build_thickness_scene(PLOTTER, res["mesh"], params=params,
                                  side_label=_side_label(side_key))
            s = res["stats"]
            html_out = _meta_html() + _stat_rows(
                f"Thickness — {_side_label(side_key)} (mm)",
                [("mean", f"{s['mean']:.3f}"), ("median", f"{s['median']:.3f}"),
                 ("sd", f"{s['sd']:.3f}"), ("min", f"{s['min']:.3f}"),
                 ("max", f"{s['max']:.3f}"), ("n vertices", f"{s['n']:,}")],
            ) + _stat_rows("Segmentation",
                           [("region label", str(res["region_label"])),
                            ("metal fraction", f"{res['metal_fraction']:.4f}")])
        else:  # Mode B deviation
            ref = sides.get(state.ref_side)
            tgt = sides.get(state.tgt_side)
            if ref is None or tgt is None:
                raise RuntimeError("Reference/target side unknown.")
            if state.ref_side == state.tgt_side:
                raise RuntimeError("Choose two different sides for deviation.")
            manual = _manual_transform_matrix()
            res = pipeline.compare_sides(ref, tgt, params, manual_transform=manual)
            _LAST_MESH["deviation"] = res["mesh"]
            build_deviation_scene(PLOTTER, res["mesh"], params=params)
            st = res["stats"]
            reg = res["registration"]
            html_out = _meta_html() + _stat_rows(
                "Registration",
                [("RMS (mm)", f"{reg['rms']:.3f}"),
                 ("inlier fraction", f"{reg['inlier_fraction']:.3f}"),
                 ("manual nudge", "yes" if reg.get("manual_adjusted") else "no"),
                 ("reference", _side_label(state.ref_side)),
                 ("target", _side_label(state.tgt_side))],
            ) + _stat_rows(
                "Signed deviation (mm)",
                [("mean", f"{st['mean']:.3f}"), ("median", f"{st['median']:.3f}"),
                 ("sd", f"{st['sd']:.3f}"),
                 ("max +", f"{st['max_positive']:.3f}"),
                 ("max −", f"{st['max_negative']:.3f}"),
                 ("added vol (cc)", f"{st['added_volume_cc']:.2f}"),
                 ("removed vol (cc)", f"{st['removed_volume_cc']:.2f}")],
            )

        # SUPERSEDE guard: if a newer change landed while this compute ran, drop
        # our result silently — the newer request owns the viewport now.
        if req_id is not None and not _is_current(req_id):
            return

        _enable_hover()
        with state:
            state.stats_html = html_out
            state.status = "done"
            state.status_msg = "Recompute complete."
        if ctrl.view_update:
            ctrl.view_update()
        state.flush()

        # After the first thickness compute for the active side, lazily load the
        # per-region preview thumbnails (cached per session/side). Skipped for
        # the deviation view and mesh sessions inside the loader.
        if wants_thickness:
            load_region_thumbnails()
    except Exception as e:  # noqa: BLE001
        # Don't surface an error from a compute that has already been superseded.
        if req_id is not None and not _is_current(req_id):
            return
        traceback.print_exc()
        with state:
            state.status = "error"
            state.status_msg = f"Compute failed: {e}"
        state.flush()


def _side_label(name: str) -> str:
    return {"left": "Left", "right": "Right", "full": "Full",
            "mesh": "Mesh"}.get(name, name.capitalize())


def _computing_msg() -> str:
    return ("Computing… (Mode B deviation involves registration and can take a "
            "while)" if (state.mode == "B" and state.b_view == "deviation")
            else "Computing…")


def recompute(*_a, **_k):
    """Kick off a background recompute NOW with the CURRENT params/mode/side.

    Bumps the request id so any in-flight/pending compute is superseded — the
    UI never stalls and an older result can't overwrite this one. Used both by
    the manual "Apply / Recompute" button and by the debounced auto path.
    """
    req_id = _next_request_id()
    with state:
        state.status = "computing"
        state.status_msg = _computing_msg()
    state.flush()
    threading.Thread(target=_compute_worker, args=(req_id,), daemon=True).start()


def schedule_recompute(*_a, **_k):
    """Debounced auto-recompute: coalesce rapid changes into ONE compute.

    Re-arms a ~600 ms timer on every call; only the last change in a burst
    actually fires ``recompute``. A "computing…" status is shown immediately so
    the user sees the pending state while they keep dragging. Coloring stays
    instant during the wait because display-only knobs never route here.
    """
    global _DEBOUNCE_TIMER
    if not SESSION.get("sides"):
        return  # nothing loaded yet; nothing to compute
    with _REQ_LOCK:
        if _DEBOUNCE_TIMER is not None:
            _DEBOUNCE_TIMER.cancel()
        _DEBOUNCE_TIMER = threading.Timer(RECOMPUTE_DEBOUNCE_S, recompute)
        _DEBOUNCE_TIMER.daemon = True
        _DEBOUNCE_TIMER.start()
    # Show the pending indicator right away (non-blocking; UI stays interactive).
    if state.status != "computing":
        with state:
            state.status = "computing"
            state.status_msg = _computing_msg()
        state.flush()


ctrl.recompute = recompute
ctrl.schedule_recompute = schedule_recompute


# --------------------------------------------------------------------------- #
# Instant DISPLAY-ONLY re-render (no server recompute).
#
# Colormap / range / colorbar-steps / reverse / center / |range| / view changes
# only affect how the EXISTING geometry is colored or framed. We re-run the
# pyvista scene builder on the LAST computed mesh with the new params — updating
# the LUT / scalar-bar / camera in place — without touching the pipeline. This
# stays instant even while a recompute is running in the background.
# --------------------------------------------------------------------------- #
def apply_display_only(*_a, **_k):
    """Recolor the current surface from the last mesh using the live params."""
    params = _params_from_state()
    diverging = state.mode == "B" and state.b_view == "deviation"
    mesh = _LAST_MESH["deviation"] if diverging else _LAST_MESH["thickness"]
    if mesh is None:
        return  # nothing rendered yet; the next compute will pick up the params
    try:
        if diverging:
            build_deviation_scene(PLOTTER, mesh, params=params)
        else:
            build_thickness_scene(PLOTTER, mesh, params=params,
                                  side_label=_side_label(state.side))
        _enable_hover()
        if ctrl.view_update:
            ctrl.view_update()
    except Exception:  # noqa: BLE001
        traceback.print_exc()


ctrl.apply_display_only = apply_display_only


# --------------------------------------------------------------------------- #
# Wire realtime reactivity: bind every control to the right path so ANY change
# reflects automatically — no Apply click required.
#
#   * recompute=True params  -> debounced background recompute (superseding)
#   * display-only params    -> instant client-side recolor/reframe (no compute)
#   * session selectors       -> recompute (side/mode/b_view/ref/tgt)
#   * manual-anchor knobs     -> recompute (only bite when manual_enabled)
#
# Parity is preserved: which params are display-only vs recompute comes straight
# from the registry (``P.DISPLAY_ONLY_KEYS`` / the ``recompute`` flag the API
# also serves), so the two frontends agree on the classification.
# --------------------------------------------------------------------------- #
_RECOMPUTE_PARAM_KEYS = [c["key"] for c in control_specs() if c["recompute"]]
_DISPLAY_ONLY_PARAM_KEYS = [c["key"] for c in control_specs() if not c["recompute"]]
# Non-registry selectors / knobs that also require a fresh pipeline run.
_RECOMPUTE_STATE_KEYS = [
    "side", "mode", "b_view", "ref_side", "tgt_side",
    "manual_enabled", "manual_tx", "manual_ty", "manual_tz",
    "manual_rx", "manual_ry", "manual_rz",
]

for _k in _RECOMPUTE_PARAM_KEYS + _RECOMPUTE_STATE_KEYS:
    state.change(_k)(schedule_recompute)
for _k in _DISPLAY_ONLY_PARAM_KEYS:
    state.change(_k)(apply_display_only)

# MPR reactivity: a plane slider moves -> mirror to crosshair + re-render;
# window/level changes -> re-render all three panels. These are display-only for
# the 2D panels and never touch the 3D pipeline (no recompute).
for _k in ("mpr_idx_axial", "mpr_idx_coronal", "mpr_idx_sagittal"):
    state.change(_k)(_mpr_on_plane_index_change)
for _k in ("mpr_window", "mpr_level"):
    state.change(_k)(_mpr_refresh_images)
# Switching the thickness side re-points the MPR viewer at that volume.
state.change("side")(_mpr_reset_for_side)


# --------------------------------------------------------------------------- #
# Export: build a multi-format bundle via core.export.export_bundle and expose
# each result as a real download link served from /downloads.
# --------------------------------------------------------------------------- #
def _camera_from_state() -> dict:
    return {
        "azimuth": float(state.cam_azimuth),
        "elevation": float(state.cam_elevation),
        "roll": float(state.cam_roll),
        "zoom": float(state.cam_zoom),
    }


def _export_worker():
    try:
        params = _params_from_state()
        with _LOCK:
            sides = dict(SESSION["sides"])
            is_mesh_sess = bool(SESSION["is_mesh"])
        formats = list(state.export_formats or [])
        if not formats:
            raise RuntimeError("Pick at least one export format.")
        dpi = int(state.export_dpi)
        if dpi <= 0:
            raise RuntimeError("DPI must be positive.")

        mode = state.mode
        diverging = mode == "B" and state.b_view == "deviation"
        if diverging:
            ref = sides.get(state.ref_side)
            tgt = sides.get(state.tgt_side)
            if ref is None or tgt is None or state.ref_side == state.tgt_side:
                raise RuntimeError("Mode B export needs two distinct sides.")
            res = pipeline.compare_sides(ref, tgt, params,
                                         manual_transform=_manual_transform_matrix())
            mesh, scalar = res["mesh"], res["scalar"]
        else:
            if is_mesh_sess:
                raise RuntimeError(
                    "Thickness export needs a volume; this is a surface mesh.")
            side = sides.get(state.side)
            if side is None:
                raise RuntimeError(f"Unknown side '{state.side}'.")
            res = pipeline.analyze_thickness(side["arr"], side["spacing"], params,
                                             offset_xyz=side["offset_xyz"])
            mesh, scalar = res["mesh"], "thickness_mm"

        key = uuid.uuid4().hex[:12]
        out_dir = EXPORTS_DIR / key
        files = export_bundle(mesh, scalar, params, out_dir,
                              formats=tuple(f.lower() for f in formats),
                              dpi=dpi, camera=_camera_from_state(),
                              diverging=diverging, stem="export")
        links = [{"fmt": fmt, "url": f"/downloads/{key}/{Path(p).name}"}
                 for fmt, p in files.items()]
        with state:
            state.export_links = links
            state.export_busy = False
            state.export_msg = f"Exported {len(links)} file(s)."
        state.flush()
    except Exception as e:  # noqa: BLE001
        traceback.print_exc()
        with state:
            state.export_busy = False
            state.export_msg = f"Export failed: {e}"
            state.export_links = []
        state.flush()


def do_export(*_a, **_k):
    if state.export_busy:
        return
    with state:
        state.export_busy = True
        state.export_msg = "Exporting…"
        state.export_links = []
    state.flush()
    threading.Thread(target=_export_worker, daemon=True).start()


ctrl.do_export = do_export


# --------------------------------------------------------------------------- #
# Share / switcher actions.
# --------------------------------------------------------------------------- #
def refresh_config(*_a, **_k):
    cfg = read_public_config()
    with state:
        state.cfg_public = cfg["public"]
        state.cfg_trame_url = cfg["trame_url"] or ""
        state.cfg_react_url = cfg["react_url"] or ""
        state.share_url = cfg["trame_url"] or FALLBACK_TRAME_URL
        state.other_ui_url = cfg["react_url"] or FALLBACK_REACT_URL
    state.flush()


ctrl.refresh_config = refresh_config

# Poll interval for the Share panel's live public-URL refresh (seconds). Mirrors
# the React app's 6 s /api/config poll: when scripts/share.sh (re)starts a tunnel
# after sleep/wake, the shown URL updates WITHOUT a page reload.
CONFIG_POLL_S = 6.0
_config_poll_stop = threading.Event()


def _config_poll_loop() -> None:
    """Background loop: re-read outputs/public_urls.json every CONFIG_POLL_S and
    push any change to the Share panel state (so the URL refreshes live)."""
    last = None
    while not _config_poll_stop.wait(CONFIG_POLL_S):
        try:
            cfg = read_public_config()
            sig = (cfg["public"], cfg["trame_url"], cfg["react_url"])
            if sig != last:
                last = sig
                refresh_config()
        except Exception:  # noqa: BLE001
            # Transient read error (file mid-rewrite) — keep the last URL.
            pass


def start_config_poll() -> None:
    """Start the live-config polling thread once."""
    t = threading.Thread(target=_config_poll_loop, daemon=True)
    t.start()


ctrl.start_config_poll = start_config_poll


# --------------------------------------------------------------------------- #
# File upload: VFileInput yields a list of {name, content(bytes/base64), size}.
# Accepts every supported format; branches mesh vs volume, single vs bilateral.
# --------------------------------------------------------------------------- #
@state.change("upload_file")
def _on_upload(upload_file, **_k):
    if not upload_file:
        return
    entry = upload_file[0] if isinstance(upload_file, list) else upload_file
    name = entry.get("name", "upload.zip")
    content = entry.get("content")
    if content is None:
        return
    if isinstance(content, str):  # base64 fallback
        import base64
        content = base64.b64decode(content.split(",")[-1])
    dest = WORKDIR / f"upload_{uuid.uuid4().hex[:8]}_{name}"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(bytes(content))

    with state:
        state.status = "computing"
        state.status_msg = f"Ingesting {name}…"
    state.flush()

    def _job():
        try:
            _load_source(dest)
            with state:
                _refresh_session_ui()
                if SESSION.get("is_mesh"):
                    state.status_msg = ("Surface mesh loaded — Mode B "
                                        "(comparison / viewing) only.")
                elif state.is_bilateral:
                    state.status_msg = "Bilateral scan loaded (Left / Right)."
                else:
                    state.status_msg = "Single-sided scan loaded (Full)."
                state.status = "idle"
            state.flush()
            recompute()
        except Exception as e:  # noqa: BLE001
            traceback.print_exc()
            with state:
                state.status = "error"
                state.status_msg = f"Upload ingest failed: {e}"
            state.flush()

    threading.Thread(target=_job, daemon=True).start()


# --------------------------------------------------------------------------- #
# UI: registry-driven control renderer.
# --------------------------------------------------------------------------- #
def _render_control(spec: dict):
    key, label = spec["key"], spec["label"]
    unit = f" ({spec['unit']})" if spec.get("unit") else ""
    if spec["control"] == "bool":
        v3.VSwitch(v_model=(key,), label=label, density="compact",
                   hide_details=True, color="primary")
    elif spec["control"] == "enum":
        state[f"{key}_choices"] = spec.get("choices") or []
        v3.VSelect(v_model=(key,), items=(f"{key}_choices",),
                   label=label, density="compact", hide_details=True,
                   variant="outlined")
    else:  # int / float slider
        v3.VSlider(v_model=(key,), label=f"{label}{unit}",
                   min=spec.get("minimum", 0), max=spec.get("maximum", 1),
                   step=spec.get("step", 1), thumb_label=True,
                   density="compact", hide_details=True, color="primary")


with SinglePageWithDrawerLayout(server) as layout:
    layout.title.set_text("3Dorth — cortical bone mapping (trame)")

    with layout.toolbar:
        v3.VSpacer()
        html.Span("Mode", style="font-size:13px;color:#555;margin-right:8px")
        with v3.VBtnToggle(v_model=("mode", "A"), density="compact",
                           mandatory=True, variant="outlined", divided=True):
            v3.VBtn("A", value="A", disabled=("is_mesh_session",))
            v3.VBtn("B", value="B")
        v3.VSpacer()
        # Share URL (copyable) + switch-to-the-other-UI.
        v3.VTextField(
            model_value=("share_url",), readonly=True, density="compact",
            hide_details=True, variant="outlined", label="Share URL",
            style="max-width:340px;margin-right:8px", prepend_inner_icon="mdi-share-variant",
            append_inner_icon="mdi-content-copy",
            click_append_inner="navigator.clipboard && navigator.clipboard.writeText(share_url)")
        html.Span("Run ./scripts/share.sh for a public link",
                  v_if="!cfg_public",
                  style="font-size:11px;color:#b26a00;margin-right:8px;max-width:220px")
        v3.VBtn(
            "Switch to {{ other_ui_name }}", size="small", variant="tonal",
            color="primary", prepend_icon="mdi-swap-horizontal",
            style="margin-right:12px",
            click="window.location.assign(other_ui_url)")
        # progress + status
        v3.VProgressLinear(
            indeterminate=True, color="primary",
            v_if="status === 'computing'", style="max-width:120px;margin-right:12px")
        html.Span("{{ status_msg }}",
                  style="font-size:13px;color:#444;max-width:280px;"
                        "overflow:hidden;text-overflow:ellipsis;white-space:nowrap")

    with layout.drawer as drawer:
        drawer.width = 380
        with v3.VCard(flat=True, classes="pa-2"):
            # ---- Session: side + Mode B sub-view + Apply ---------------------
            v3.VCardTitle("Session", classes="text-subtitle-1 pb-1")
            v3.VSelect(v_model=("side",), items=("side_options",),
                       label="Side (thickness view)", density="compact",
                       hide_details=True, variant="outlined",
                       disabled=("is_mesh_session",))
            html.Div(
                "Surface mesh loaded — cortical thickness needs a volume, so "
                "Mode A is disabled. Use Mode B (comparison / viewing).",
                v_if="is_mesh_session",
                style="font-size:11px;color:#b26a00;margin-top:4px;line-height:1.4")
            # Mode B: reference / target / sub-view selector
            with html.Div(v_if="mode === 'B'", classes="mt-2"):
                with v3.VBtnToggle(v_model=("b_view", "thickness"),
                                   density="compact", mandatory=True,
                                   variant="outlined", divided=True,
                                   classes="mb-2"):
                    v3.VBtn("Thickness", value="thickness",
                            disabled=("is_mesh_session",))
                    v3.VBtn("Deviation", value="deviation")
                v3.VSelect(v_model=("ref_side",), items=("side_options",),
                           label="Reference side (on top)", density="compact",
                           hide_details=True, variant="outlined", classes="mb-1")
                v3.VSelect(v_model=("tgt_side",), items=("side_options",),
                           label="Target side", density="compact",
                           hide_details=True, variant="outlined")

            # ---- Region picker (visual thumbnails) ---------------------------
            # Only meaningful for the thickness view of a volume side. Each region
            # shows a small rendered preview + volume/boneness; clicking one
            # selects it and recomputes. The text side-selector above still works.
            with html.Div(
                v_if="!is_mesh_session && !(mode === 'B' && b_view === 'deviation')",
                classes="mt-3"):
                v3.VCardSubtitle("Region (click a preview to select)",
                                 classes="px-0 pb-1")
                # Spinner while the previews render (~5-10 s).
                with html.Div(v_if="region_thumbs_loading",
                              classes="d-flex align-center",
                              style="gap:8px;font-size:12px;color:#666;"
                                    "margin:4px 0"):
                    v3.VProgressCircular(indeterminate=True, size="18", width="2",
                                         color="primary")
                    html.Span("{{ region_thumbs_msg }}")
                html.Div("{{ region_thumbs_msg }}",
                         v_if="!region_thumbs_loading && region_thumbs.length === 0",
                         style="font-size:11px;color:#888;margin:4px 0")
                # One clickable card per region.
                with html.Div(v_if="region_thumbs.length > 0",
                              style="display:flex;flex-direction:column;gap:6px;"
                                    "margin-top:4px"):
                    with html.Template(v_for="r in region_thumbs", key="r.label"):
                        with html.Div(
                            click=(ctrl.select_region, "[r.label]"),
                            classes="d-flex align-center",
                            style=("gap:10px;padding:5px 7px;border:1px solid #ddd;"
                                   "border-radius:7px;cursor:pointer;background:#fff"),
                        ):
                            # thumbnail image (or a placeholder chip if null)
                            html.Img(
                                v_if="r.thumb",
                                src=("r.thumb",),
                                style="width:64px;height:64px;object-fit:contain;"
                                      "border:1px solid #eee;border-radius:5px;"
                                      "flex:0 0 auto;background:#fff")
                            html.Div(
                                "no preview", v_if="!r.thumb",
                                style="width:64px;height:64px;display:flex;"
                                      "align-items:center;justify-content:center;"
                                      "border:1px solid #eee;border-radius:5px;"
                                      "flex:0 0 auto;font-size:10px;color:#999;"
                                      "text-align:center")
                            with html.Div(style="min-width:0"):
                                html.Div(
                                    "Region {{ r.label }}",
                                    style="font-size:13px;font-weight:600;color:#222")
                                html.Div(
                                    "{{ r.volume_cm3.toFixed(1) }} cm³ · "
                                    "bone {{ r.boneness.toFixed(2) }}",
                                    style="font-size:11px;color:#1867c0;"
                                          "font-variant-numeric:tabular-nums")

            # Changes now auto-recompute (debounced); this button is an OPTIONAL
            # manual "recompute now" — it is no longer required.
            v3.VBtn("Recompute now", block=True, color="primary",
                    classes="mt-3", click=ctrl.recompute,
                    loading=("status === 'computing'",),
                    prepend_icon="mdi-refresh", variant="tonal")
            html.Div(
                "Every change applies automatically — coloring instantly, "
                "analysis after a brief pause. This button just forces it now.",
                style="font-size:11px;color:#888;margin-top:4px;line-height:1.4")

            v3.VDivider(classes="my-3")

            # ---- File upload (all formats) -----------------------------------
            v3.VCardSubtitle("Load a scan or surface", classes="px-0 pb-1")
            v3.VFileInput(
                v_model=("upload_file", None),
                label="Upload .zip .nii .nii.gz .stl .ply .obj .vtp",
                accept=".zip,.nii,.nii.gz,.stl,.ply,.obj,.vtp",
                density="compact", hide_details=True, variant="outlined",
                prepend_icon="mdi-upload")

            v3.VDivider(classes="my-3")

            # ---- Status alert ------------------------------------------------
            v3.VAlert(
                text=("status_msg",), density="compact", variant="tonal",
                type=("status === 'error' ? 'error' : "
                      "(status === 'computing' ? 'info' : 'success')",),
                classes="mb-3", style="font-size:12px")

            # ---- Live stats --------------------------------------------------
            html.Div(v_html=("stats_html",),
                     style="background:#fafafa;border:1px solid #eee;"
                           "border-radius:6px;padding:8px;margin-bottom:8px")

        # ---- Expansion panels: params + Mode B manual anchor + Export --------
        groups: dict[str, list] = {}
        for c in control_specs():
            groups.setdefault(c["group"], []).append(c)
        with v3.VExpansionPanels(multiple=True, variant="accordion"):
            # Registry-driven parameter panel (parity with React).
            for group, specs in groups.items():
                with v3.VExpansionPanel(title=group):
                    with v3.VExpansionPanelText():
                        for spec in specs:
                            _render_control(spec)

            # Manual anchor (Mode B) — only meaningful for a comparison.
            with v3.VExpansionPanel(title="Manual anchor (Mode B)"):
                with v3.VExpansionPanelText():
                    html.Div(
                        "Nudge the auto-registration: translate/rotate the target "
                        "over the reference. Changes auto-recompute (debounced). "
                        "Use the reference/target selectors above to choose which "
                        "side is on top.",
                        style="font-size:11px;color:#666;margin-bottom:8px;line-height:1.4")
                    v3.VSwitch(v_model=("manual_enabled",),
                               label="Apply manual nudge", density="compact",
                               hide_details=True, color="primary", classes="mb-2")
                    html.Div("Translation (mm)",
                             style="font-size:11px;font-weight:700;color:#333;margin:4px 0")
                    v3.VSlider(v_model=("manual_tx",), label="x", min=-20, max=20,
                               step=0.5, thumb_label=True, density="compact",
                               hide_details=True, disabled=("!manual_enabled",))
                    v3.VSlider(v_model=("manual_ty",), label="y", min=-20, max=20,
                               step=0.5, thumb_label=True, density="compact",
                               hide_details=True, disabled=("!manual_enabled",))
                    v3.VSlider(v_model=("manual_tz",), label="z", min=-20, max=20,
                               step=0.5, thumb_label=True, density="compact",
                               hide_details=True, disabled=("!manual_enabled",))
                    html.Div("Rotation (deg)",
                             style="font-size:11px;font-weight:700;color:#333;margin:8px 0 4px")
                    v3.VSlider(v_model=("manual_rx",), label="rx", min=-30, max=30,
                               step=0.5, thumb_label=True, density="compact",
                               hide_details=True, disabled=("!manual_enabled",))
                    v3.VSlider(v_model=("manual_ry",), label="ry", min=-30, max=30,
                               step=0.5, thumb_label=True, density="compact",
                               hide_details=True, disabled=("!manual_enabled",))
                    v3.VSlider(v_model=("manual_rz",), label="rz", min=-30, max=30,
                               step=0.5, thumb_label=True, density="compact",
                               hide_details=True, disabled=("!manual_enabled",))
                    v3.VBtn("Recompute now", block=True, size="small",
                            color="primary", variant="tonal", classes="mt-3",
                            prepend_icon="mdi-refresh",
                            click=ctrl.recompute)

            # Export panel.
            with v3.VExpansionPanel(title="Export"):
                with v3.VExpansionPanelText():
                    v3.VSelect(
                        v_model=("export_formats",),
                        items=("export_format_choices",),
                        label="Formats", multiple=True, chips=True,
                        density="compact", hide_details=True, variant="outlined",
                        classes="mb-2")
                    v3.VTextField(
                        v_model=("export_dpi",), label="DPI (raster)",
                        type="number", density="compact", hide_details=True,
                        variant="outlined", classes="mb-2")
                    html.Div("Camera pose",
                             style="font-size:11px;font-weight:700;color:#333;margin:4px 0")
                    v3.VSlider(v_model=("cam_azimuth",), label="azimuth°",
                               min=-180, max=180, step=1, thumb_label=True,
                               density="compact", hide_details=True)
                    v3.VSlider(v_model=("cam_elevation",), label="elevation°",
                               min=-90, max=90, step=1, thumb_label=True,
                               density="compact", hide_details=True)
                    v3.VSlider(v_model=("cam_roll",), label="roll°",
                               min=-180, max=180, step=1, thumb_label=True,
                               density="compact", hide_details=True)
                    v3.VSlider(v_model=("cam_zoom",), label="zoom",
                               min=0.2, max=4.0, step=0.1, thumb_label=True,
                               density="compact", hide_details=True)
                    v3.VBtn("Export", block=True, color="primary",
                            classes="mt-3", click=ctrl.do_export,
                            loading=("export_busy",),
                            disabled=("export_busy",))
                    v3.VAlert(text=("export_msg",), v_if="export_msg",
                              density="compact", variant="tonal",
                              type=("export_msg.startsWith('Export failed') ? "
                                    "'error' : 'success'",),
                              classes="mt-2", style="font-size:12px")
                    # Real download links (one per exported format).
                    with html.Div(classes="mt-2",
                                  style="display:flex;flex-wrap:wrap;gap:6px"):
                        with html.Template(
                                v_for="link in export_links",
                                key="link.fmt"):
                            html.A(
                                "{{ link.fmt }}",
                                href=("link.url",), download=True,
                                target="_blank",
                                style="display:inline-block;padding:4px 10px;"
                                      "background:#1867c0;color:#fff;border-radius:4px;"
                                      "font-size:12px;text-decoration:none;"
                                      "text-transform:uppercase;font-weight:600")

    with layout.content:
        with v3.VContainer(fluid=True, classes="fill-height pa-0",
                           style="position:relative"):
            # Split the content: 3D view (flex) + MPR column (fixed, scrolls).
            with html.Div(style="display:flex;flex-direction:row;width:100%;"
                                 "height:100%;min-height:0"):
                # ---- 3D view (left) --------------------------------------- #
                with html.Div(style="position:relative;flex:1 1 auto;"
                                     "min-width:0;height:100%"):
                    view = plotter_ui(PLOTTER)
                    ctrl.view_update = view.update
                    # Hover tooltip overlay (top-right of the 3D pane).
                    html.Div(
                        v_html=("hover_html",),
                        v_show="hover_active",
                        style="position:absolute;top:12px;right:12px;z-index:10;"
                              "background:rgba(20,22,28,.92);color:#fff;"
                              "padding:8px 12px;border-radius:8px;max-width:260px;"
                              "pointer-events:none;line-height:1.4;"
                              "box-shadow:0 2px 12px rgba(0,0,0,.35)")

                # ---- MPR column (right): 3 array-oriented slice panels ----- #
                with html.Div(
                    v_show="mpr_available",
                    style="flex:0 0 360px;height:100%;overflow-y:auto;"
                          "border-left:1px solid #e0e0e0;background:#0f1116;"
                          "padding:10px 12px;box-sizing:border-box"):
                    html.Div(
                        "MPR — array-oriented slices",
                        style="color:#e8e8e8;font-size:13px;font-weight:700;"
                              "letter-spacing:.02em;margin-bottom:2px")
                    html.Div(
                        "Side: {{ mpr_side }} · voxel "
                        "({{ mpr_ix }}, {{ mpr_iy }}, {{ mpr_iz }}) · "
                        "click the 3D surface to move the crosshair",
                        style="color:#9aa0aa;font-size:11px;margin-bottom:6px;"
                              "line-height:1.4")
                    html.Div(
                        "{{ mpr_note }}",
                        style="color:#c9a227;font-size:10px;margin-bottom:10px;"
                              "line-height:1.4;border:1px solid #4a3f12;"
                              "background:#1c1808;border-radius:6px;padding:5px 7px")

                    # Window / level for the 2D panels (bone default).
                    with html.Div(style="margin-bottom:8px"):
                        v3.VSlider(
                            v_model=("mpr_window",), label="Window (HU)",
                            min=1, max=4000, step=1, thumb_label=True,
                            density="compact", hide_details=True, color="cyan",
                            style="color:#cfd3da")
                        v3.VSlider(
                            v_model=("mpr_level",), label="Level (HU)",
                            min=-1000, max=2000, step=1, thumb_label=True,
                            density="compact", hide_details=True, color="cyan",
                            style="color:#cfd3da")

                    # One panel per plane: label "(array orientation)", the slice
                    # image, and a slider bound to that plane's slice index.
                    def _mpr_panel(title, img_key, idx_key, n_key):
                        with html.Div(style="margin-bottom:12px"):
                            html.Div(
                                title,
                                style="color:#cfd3da;font-size:12px;"
                                      "font-weight:600;margin-bottom:3px")
                            html.Img(
                                src=(img_key,),
                                v_if=f"{img_key}",
                                style="width:100%;height:auto;display:block;"
                                      "background:#000;border:1px solid #2a2e36;"
                                      "border-radius:5px;image-rendering:pixelated")
                            v3.VSlider(
                                v_model=(idx_key,), min=0,
                                max=(f"{n_key} - 1",), step=1,
                                thumb_label=True, density="compact",
                                hide_details=True, color="cyan",
                                classes="mt-1", style="color:#cfd3da")

                    _mpr_panel("Axial (array orientation)", "mpr_img_axial",
                               "mpr_idx_axial", "mpr_n_axial")
                    _mpr_panel("Coronal (array orientation)", "mpr_img_coronal",
                               "mpr_idx_coronal", "mpr_n_coronal")
                    _mpr_panel("Sagittal (array orientation)", "mpr_img_sagittal",
                               "mpr_idx_sagittal", "mpr_n_sagittal")


# --------------------------------------------------------------------------- #
# Startup: load the demo scan (server-side) and do an initial Mode A compute.
# --------------------------------------------------------------------------- #
def _bootstrap():
    refresh_config()
    start_config_poll()  # live Share-URL refresh (mirrors React's 6 s poll)
    if DEMO_ZIP is None:
        with state:
            state.status = "error"
            state.status_msg = ("No demo dataset found. Build one with "
                                "scripts/make_demo.py, or upload a scan.")
        state.flush()
        return
    try:
        _load_source(DEMO_ZIP, layout="bilateral")
        with state:
            _refresh_session_ui()
            state.status_msg = "Demo scan loaded. Computing…"
        state.flush()
        recompute()
    except Exception as e:  # noqa: BLE001
        traceback.print_exc()
        with state:
            state.status = "error"
            state.status_msg = f"Startup load failed: {e}"
        state.flush()


if __name__ == "__main__":
    _bootstrap()
    server.start(port=8081)
