"""Frontend 1 — trame + pyvista (server-side VTK rendering).

This UI calls the Python ``core`` DIRECTLY (trame is server-side); it does NOT go
through the HTTP API. It reaches parity with the React frontend:

  * Controls are generated by iterating the parameter registry (``control_specs``)
    — the param list is never hardcoded, so the two UIs cannot drift.
  * A SIDE selector (Left / Right) picks which half of a bilateral scan to view.
  * An "Apply / Recompute" button re-runs ``core.pipeline`` with the CURRENT
    parameter values and swaps in the freshly computed geometry — so EVERY
    side-panel parameter actually applies to the view.
  * A Mode A / Mode B toggle. Mode A = single-side cortical thickness. Mode B adds
    a per-side THICKNESS view AND a two-side signed-DEVIATION view (diverging
    blue-white-red colormap) with registration RMS + deviation stats.
  * A file-upload control ingests an uploaded .zip via
    ``pipeline.load_volume_from_source`` and starts a new session.

Heavy compute runs on a background thread so the server stays responsive; a
"computing…" status is shown while it runs.

Run:  .venv/bin/python -m app_trame.app   (serves on http://localhost:8080)
"""

from __future__ import annotations

import sys
import threading
import traceback
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import pyvista as pv  # noqa: E402
from pyvista.trame.ui import plotter_ui  # noqa: E402
from trame.app import get_server  # noqa: E402
from trame.ui.vuetify3 import SinglePageWithDrawerLayout  # noqa: E402
from trame.widgets import html  # noqa: E402
from trame.widgets import vuetify3 as v3  # noqa: E402

import core.parameters as P  # noqa: E402
from app_trame.controls import control_specs  # noqa: E402
from app_trame.scene import build_deviation_scene, build_thickness_scene  # noqa: E402
from core import pipeline  # noqa: E402

pv.OFF_SCREEN = True

WORKDIR = ROOT / "data" / "raw"
DEMO_DIR = ROOT / "Bilateral Omuz BT Jul 4 2026"
DEMO_ZIP = next(DEMO_DIR.glob("*.zip"), None) if DEMO_DIR.exists() else None

server = get_server(client_type="vue3")
state, ctrl = server.state, server.controller

PLOTTER = pv.Plotter(off_screen=True)

# --------------------------------------------------------------------------- #
# Server-side session (a loaded scan split into left/right sides). Guarded by a
# lock because the background compute thread reads it while the UI may reload it.
# --------------------------------------------------------------------------- #
SESSION: dict = {"arr": None, "spacing": None, "meta": None, "sides": {}}
_LOCK = threading.Lock()
_LAST_MESH = {"thickness": None, "deviation": None}


def _load_session(source) -> None:
    arr, spacing, meta = pipeline.load_volume_from_source(source, WORKDIR)
    sides = pipeline.split_sides(arr, spacing)
    with _LOCK:
        SESSION.update(arr=arr, spacing=spacing, meta=meta, sides=sides)


# --------------------------------------------------------------------------- #
# State: registry defaults + UI-only knobs.
# --------------------------------------------------------------------------- #
for _c in control_specs():
    state[_c["key"]] = _c["default"]

state.mode = "A"                 # "A" or "B"
state.side = "left"              # active side for thickness views
state.ref_side = "left"          # Mode B reference
state.tgt_side = "right"         # Mode B target
state.b_view = "thickness"       # Mode B sub-view: "thickness" or "deviation"
state.status = "idle"            # "idle" | "computing" | "done" | "error"
state.status_msg = "Ready."
state.stats_html = ""
state.meta_html = ""
state.side_options = [{"title": "Left", "value": "left"},
                      {"title": "Right", "value": "right"}]


def _params_from_state() -> "P.Parameters":
    updates = {c["key"]: state[c["key"]] for c in control_specs()
               if state[c["key"]] is not None}
    return P.Parameters(**updates)


# --------------------------------------------------------------------------- #
# Stats / meta rendering (HTML, no overlap: simple definition rows).
# --------------------------------------------------------------------------- #
def _stat_rows(title: str, items: list[tuple[str, str]]) -> str:
    rows = "".join(
        f"<div style='display:flex;justify-content:space-between;gap:12px;"
        f"padding:1px 0;font-size:12px;line-height:1.5'>"
        f"<span style='color:#555'>{k}</span>"
        f"<span style='font-variant-numeric:tabular-nums;font-weight:600'>{v}</span></div>"
        for k, v in items
    )
    return (f"<div style='margin-bottom:8px'>"
            f"<div style='font-size:11px;font-weight:700;letter-spacing:.04em;"
            f"text-transform:uppercase;color:#333;margin-bottom:2px'>{title}</div>"
            f"{rows}</div>")


def _meta_html() -> str:
    m = SESSION.get("meta") or {}
    if not m:
        return "<div style='font-size:12px;color:#888'>No scan loaded.</div>"
    items = [
        ("Series", str(m.get("series", "—"))),
        ("Shape (z,y,x)", "×".join(str(s) for s in m.get("shape", []))),
        ("Spacing (mm)", "×".join(str(s) for s in m.get("spacing_mm", []))),
        ("Laterality", str(m.get("laterality", "—"))),
    ]
    return _stat_rows("Loaded scan", items)


# --------------------------------------------------------------------------- #
# Compute (runs on a background thread).
# --------------------------------------------------------------------------- #
def _compute_worker():
    try:
        params = _params_from_state()
        with _LOCK:
            sides = dict(SESSION["sides"])
        if not sides:
            raise RuntimeError("No scan loaded.")

        mode = state.mode
        if mode == "A" or (mode == "B" and state.b_view == "thickness"):
            side_key = state.side
            side = sides.get(side_key)
            if side is None:
                raise RuntimeError(f"Unknown side '{side_key}'.")
            res = pipeline.analyze_thickness(
                side["arr"], side["spacing"], params,
                region_label=None, offset_xyz=side["offset_xyz"],
            )
            _LAST_MESH["thickness"] = res["mesh"]
            build_thickness_scene(PLOTTER, res["mesh"], params=params,
                                  side_label=side_key.capitalize())
            s = res["stats"]
            html_out = _meta_html() + _stat_rows(
                f"Thickness — {side_key.capitalize()} (mm)",
                [("mean", f"{s['mean']:.3f}"), ("median", f"{s['median']:.3f}"),
                 ("sd", f"{s['sd']:.3f}"), ("min", f"{s['min']:.3f}"),
                 ("max", f"{s['max']:.3f}"), ("n vertices", f"{s['n']:,}")],
            ) + _stat_rows("Segmentation",
                           [("region label", str(res["region_label"])),
                            ("metal fraction", f"{res['metal_fraction']:.4f}")])
        else:  # Mode B deviation
            ref = sides.get(state.ref_side)
            tgt = sides.get(state.tgt_side)
            if ref is None or tgt is None:
                raise RuntimeError("Reference/target side unknown.")
            if state.ref_side == state.tgt_side:
                raise RuntimeError("Choose two different sides for deviation.")
            res = pipeline.compare_sides(ref, tgt, params)
            _LAST_MESH["deviation"] = res["mesh"]
            build_deviation_scene(PLOTTER, res["mesh"], params=params)
            st = res["stats"]
            reg = res["registration"]
            html_out = _meta_html() + _stat_rows(
                "Registration",
                [("RMS (mm)", f"{reg['rms']:.3f}"),
                 ("inlier fraction", f"{reg['inlier_fraction']:.3f}"),
                 ("reference", state.ref_side.capitalize()),
                 ("target", state.tgt_side.capitalize())],
            ) + _stat_rows(
                "Signed deviation (mm)",
                [("mean", f"{st['mean']:.3f}"), ("median", f"{st['median']:.3f}"),
                 ("sd", f"{st['sd']:.3f}"),
                 ("max +", f"{st['max_positive']:.3f}"),
                 ("max −", f"{st['max_negative']:.3f}"),
                 ("added vol (cc)", f"{st['added_volume_cc']:.2f}"),
                 ("removed vol (cc)", f"{st['removed_volume_cc']:.2f}")],
            )

        with state:
            state.stats_html = html_out
            state.status = "done"
            state.status_msg = "Recompute complete."
        if ctrl.view_update:
            ctrl.view_update()
        state.flush()
    except Exception as e:  # noqa: BLE001
        traceback.print_exc()
        with state:
            state.status = "error"
            state.status_msg = f"Compute failed: {e}"
        state.flush()


def recompute(*_a, **_k):
    """Kick off a background recompute with the CURRENT params/mode/side."""
    if state.status == "computing":
        return
    with state:
        state.status = "computing"
        state.status_msg = ("Computing… (Mode B deviation involves registration "
                            "and can take a while)" if (state.mode == "B" and
                            state.b_view == "deviation") else "Computing…")
    state.flush()
    threading.Thread(target=_compute_worker, daemon=True).start()


ctrl.recompute = recompute


# --------------------------------------------------------------------------- #
# File upload: VFileInput yields a list of {name, content(bytes/base64), size}.
# --------------------------------------------------------------------------- #
@state.change("upload_file")
def _on_upload(upload_file, **_k):
    if not upload_file:
        return
    entry = upload_file[0] if isinstance(upload_file, list) else upload_file
    name = entry.get("name", "upload.zip")
    content = entry.get("content")
    if content is None:
        return
    if isinstance(content, str):  # base64 fallback
        import base64
        content = base64.b64decode(content.split(",")[-1])
    dest = WORKDIR / f"upload_{name}"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(bytes(content))

    with state:
        state.status = "computing"
        state.status_msg = f"Ingesting {name}…"
    state.flush()

    def _job():
        try:
            _load_session(dest)
            with state:
                state.meta_html = _meta_html()
                state.status = "idle"
                state.status_msg = "Upload loaded. Hit Apply / Recompute."
            state.flush()
            recompute()
        except Exception as e:  # noqa: BLE001
            traceback.print_exc()
            with state:
                state.status = "error"
                state.status_msg = f"Upload ingest failed: {e}"
            state.flush()

    threading.Thread(target=_job, daemon=True).start()


# --------------------------------------------------------------------------- #
# UI: registry-driven control renderer.
# --------------------------------------------------------------------------- #
def _render_control(spec: dict):
    key, label = spec["key"], spec["label"]
    unit = f" ({spec['unit']})" if spec.get("unit") else ""
    if spec["control"] == "bool":
        v3.VSwitch(v_model=(key,), label=label, density="compact",
                   hide_details=True, color="primary")
    elif spec["control"] == "enum":
        state[f"{key}_choices"] = spec.get("choices") or []
        v3.VSelect(v_model=(key,), items=(f"{key}_choices",),
                   label=label, density="compact", hide_details=True,
                   variant="outlined")
    else:  # int / float slider
        v3.VSlider(v_model=(key,), label=f"{label}{unit}",
                   min=spec.get("minimum", 0), max=spec.get("maximum", 1),
                   step=spec.get("step", 1), thumb_label=True,
                   density="compact", hide_details=True, color="primary")


with SinglePageWithDrawerLayout(server) as layout:
    layout.title.set_text("3Dorth — cortical bone mapping (trame)")

    with layout.toolbar:
        v3.VSpacer()
        html.Span("Mode", style="font-size:13px;color:#555;margin-right:8px")
        with v3.VBtnToggle(v_model=("mode", "A"), density="compact",
                           mandatory=True, variant="outlined", divided=True):
            v3.VBtn("A", value="A")
            v3.VBtn("B", value="B")
        v3.VSpacer()
        # progress + status
        v3.VProgressLinear(
            indeterminate=True, color="primary",
            v_if="status === 'computing'", style="max-width:160px;margin-right:12px")
        html.Span("{{ status_msg }}",
                  style="font-size:13px;color:#444;max-width:360px;"
                        "overflow:hidden;text-overflow:ellipsis;white-space:nowrap")

    with layout.drawer as drawer:
        drawer.width = 360
        with v3.VCard(flat=True, classes="pa-2"):
            # ---- Side + Mode B sub-view + Apply ------------------------------
            v3.VCardTitle("Session", classes="text-subtitle-1 pb-1")
            v3.VSelect(v_model=("side",), items=("side_options",),
                       label="Side (thickness view)", density="compact",
                       hide_details=True, variant="outlined")
            # Mode B: reference / target / sub-view selector
            with html.Div(v_if="mode === 'B'", classes="mt-2"):
                with v3.VBtnToggle(v_model=("b_view", "thickness"),
                                   density="compact", mandatory=True,
                                   variant="outlined", divided=True,
                                   classes="mb-2"):
                    v3.VBtn("Thickness", value="thickness")
                    v3.VBtn("Deviation", value="deviation")
                v3.VSelect(v_model=("ref_side",), items=("side_options",),
                           label="Reference side", density="compact",
                           hide_details=True, variant="outlined", classes="mb-1")
                v3.VSelect(v_model=("tgt_side",), items=("side_options",),
                           label="Target side", density="compact",
                           hide_details=True, variant="outlined")
            v3.VBtn("Apply / Recompute", block=True, color="primary",
                    classes="mt-3", click=ctrl.recompute,
                    loading=("status === 'computing'",),
                    disabled=("status === 'computing'",))

            v3.VDivider(classes="my-3")

            # ---- File upload -------------------------------------------------
            v3.VCardSubtitle("Load a bilateral scan (.zip)", classes="px-0 pb-1")
            v3.VFileInput(v_model=("upload_file", None), label="Upload DICOM .zip",
                          accept=".zip", density="compact", hide_details=True,
                          variant="outlined", prepend_icon="mdi-upload")

            v3.VDivider(classes="my-3")

            # ---- Status alert ------------------------------------------------
            v3.VAlert(
                text=("status_msg",), density="compact", variant="tonal",
                type=("status === 'error' ? 'error' : "
                      "(status === 'computing' ? 'info' : 'success')",),
                classes="mb-3", style="font-size:12px")

            # ---- Live stats --------------------------------------------------
            html.Div(v_html=("stats_html",),
                     style="background:#fafafa;border:1px solid #eee;"
                           "border-radius:6px;padding:8px;margin-bottom:8px")

        # ---- Registry-driven parameter panel (parity with React) -------------
        groups: dict[str, list] = {}
        for c in control_specs():
            groups.setdefault(c["group"], []).append(c)
        with v3.VExpansionPanels(multiple=True, variant="accordion"):
            for group, specs in groups.items():
                with v3.VExpansionPanel(title=group):
                    with v3.VExpansionPanelText():
                        for spec in specs:
                            _render_control(spec)

    with layout.content:
        with v3.VContainer(fluid=True, classes="fill-height pa-0"):
            view = plotter_ui(PLOTTER)
            ctrl.view_update = view.update


# --------------------------------------------------------------------------- #
# Startup: load the demo scan (server-side) and do an initial Mode A compute.
# --------------------------------------------------------------------------- #
def _bootstrap():
    if DEMO_ZIP is None:
        with state:
            state.status = "error"
            state.status_msg = "No demo .zip found under 'Bilateral Omuz BT Jul 4 2026'."
        state.flush()
        return
    try:
        _load_session(DEMO_ZIP)
        with state:
            state.meta_html = _meta_html()
            state.status_msg = "Demo scan loaded. Hit Apply / Recompute."
        state.flush()
        recompute()
    except Exception as e:  # noqa: BLE001
        traceback.print_exc()
        with state:
            state.status = "error"
            state.status_msg = f"Startup load failed: {e}"
        state.flush()


if __name__ == "__main__":
    _bootstrap()
    server.start()
