"""Frontend 1 — trame + pyvista (server-side VTK rendering).

Controls are generated by iterating the parameter registry (via
``control_specs``), so this UI stays at parity with the React UI by construction.
Run:  .venv/bin/python -m app_trame.app  (serves on http://localhost:8080)
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import pyvista as pv  # noqa: E402
from pyvista.trame.ui import plotter_ui  # noqa: E402
from trame.app import get_server  # noqa: E402
from trame.ui.vuetify3 import SinglePageWithDrawerLayout  # noqa: E402
from trame.widgets import vuetify3 as v3  # noqa: E402

import core.parameters as P  # noqa: E402
from app_trame.controls import control_specs  # noqa: E402
from app_trame.scene import build_scene, load_demo  # noqa: E402

pv.OFF_SCREEN = True

server = get_server(client_type="vue3")
state, ctrl = server.state, server.controller

MANIFEST, REGIONS, THICKNESS = load_demo()
PLOTTER = pv.Plotter(off_screen=True)

# initialise state from the registry defaults (so both modes' knobs exist)
for _c in control_specs():
    state[_c["key"]] = _c["default"]
state.mode = "A"
state.show_thickness = True
state.visible_labels = [r["label"] for r in MANIFEST["regions"]]
state.region_options = [
    {"title": f"Region {r['label']} ({r['volume_cm3']} cm³)"
              + (" — humerus" if r["is_humerus"] else ""), "value": r["label"]}
    for r in MANIFEST["regions"]
]
state.highlight_label = MANIFEST["thickness"]["region_label"]


def _params_from_state():
    updates = {c["key"]: state[c["key"]] for c in control_specs() if state[c["key"]] is not None}
    return P.Parameters(**updates)


def update_scene(**_kwargs):
    build_scene(
        PLOTTER, MANIFEST, REGIONS, THICKNESS,
        show_thickness=bool(state.show_thickness),
        visible_labels=list(state.visible_labels or []),
        highlight_label=state.highlight_label,
        params=_params_from_state(),
    )
    if ctrl.view_update:
        ctrl.view_update()


CTRL_KEYS = [c["key"] for c in control_specs()] + [
    "show_thickness", "visible_labels", "highlight_label",
]
state.change(*CTRL_KEYS)(update_scene)


def _render_control(spec: dict):
    key, label = spec["key"], spec["label"]
    unit = f" ({spec['unit']})" if spec.get("unit") else ""
    if spec["control"] == "bool":
        v3.VSwitch(v_model=(key,), label=label, density="compact", hide_details=True)
    elif spec["control"] == "enum":
        v3.VSelect(v_model=(key,), items=(f"{key}_choices", spec.get("choices") or []),
                   label=label, density="compact", hide_details=True)
        state[f"{key}_choices"] = spec.get("choices") or []
    else:  # int / float slider
        v3.VSlider(v_model=(key,), label=f"{label}{unit}",
                   min=spec.get("minimum", 0), max=spec.get("maximum", 1),
                   step=spec.get("step", 1), thumb_label=True, density="compact", hide_details=True)


with SinglePageWithDrawerLayout(server) as layout:
    layout.title.set_text("3Dorth — Mode A (trame)")
    with layout.toolbar:
        v3.VSpacer()
        v3.VBtnToggle(v_model=("mode", "A"), density="compact")
        v3.VSwitch(v_model=("show_thickness",), label="Thickness map", hide_details=True)

    with layout.drawer as drawer:
        drawer.width = 340
        with v3.VCard(flat=True):
            v3.VCardTitle("Layers / regions")
            v3.VSelect(v_model=("visible_labels",), items=("region_options",),
                       label="Visible regions", multiple=True, chips=True,
                       density="compact", hide_details=True)
            v3.VSelect(v_model=("highlight_label",), items=("region_options",),
                       label="Highlight region", density="compact", hide_details=True)
        # registry-driven parameter panel (parity with React)
        groups: dict[str, list] = {}
        for c in control_specs():
            groups.setdefault(c["group"], []).append(c)
        with v3.VExpansionPanels(multiple=True):
            for group, specs in groups.items():
                with v3.VExpansionPanel(title=group):
                    with v3.VExpansionPanelText():
                        for spec in specs:
                            _render_control(spec)

    with layout.content:
        with v3.VContainer(fluid=True, classes="fill-height pa-0"):
            view = plotter_ui(PLOTTER)
            ctrl.view_update = view.update

update_scene()

if __name__ == "__main__":
    server.start()
